--[[
-- File name: keymaps.lua
-- Author: Samuel Boyden
-- Date created: 2025-07-29
-- Date modified: 2025-08-10
-- All rights reserved.
--]]

-- Keymaps are automatically loaded on the VeryLazy event
-- Default keymaps that are always set: https://github.com/LazyVim/LazyVim/blob/main/lua/lazyvim/config/keymaps.lua
-- Add any additional keymaps here
